# 数学对象

In [10]:
# 标量只是一个单一的数字
scalar_value = 18
print(scalar_value)


18


In [11]:
# 标量只是一个单一的数字
scalar_value = 18
print(scalar_value, scalar_value.shape)  # 对int类型的数不能通过shape得到型


AttributeError: 'int' object has no attribute 'shape'

In [12]:
import numpy as np

# 标量只是一个单一的数字
scalar_value = 18
scalar_np = np.array(scalar_value)  # 转换为np中的数组array
print(scalar_np, "\n", scalar_np.shape)  # scalar_np为()


18 
 ()


In [13]:
# 向量是一个有序的数字数组
vector_value = [1, 2, 3]  # 这是一个列表
vector_np = np.array(vector_value)  # 转换为np中的数组array
print(
    vector_np, "\n", vector_np.shape
)  # shape显示为一维数组，其实这既不能算行向量，也不能算列向量


[1 2 3] 
 (3,)


In [14]:
# 矩阵是一个有序的二维数组，它有两个索引。第一个指向该行，第二个指向该列
matrix_list = [[1, 2, 3], [4, 5, 6]]
matrix_np = np.array(matrix_list)
print(
    "matrix_list=",
    matrix_list,
    "\n",
    "matrix_np=\n",
    matrix_np,
    "\n",
    "matrix_np.shape=",
    matrix_np.shape,
)


matrix_list= [[1, 2, 3], [4, 5, 6]] 
 matrix_np=
 [[1 2 3]
 [4 5 6]] 
 matrix_np.shape= (2, 3)


In [15]:
# 行向量的矩阵表示
vector_row = np.array([[1, 2, 3]])
print(vector_row, "\n", "shape=", vector_row.shape)


[[1 2 3]] 
 shape= (1, 3)


In [16]:
# 列向量的矩阵表示
vector_column = np.array([[4], [5], [6]])
print(vector_column, "\n", "shape=", vector_column.shape)


[[4]
 [5]
 [6]] 
 shape= (3, 1)


In [17]:
# 矩阵与标量运算
matrix_a = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix_a, "\n", "shape=", matrix_a.shape)


[[1 2 3]
 [4 5 6]] 
 shape= (2, 3)


In [18]:
# 矩阵*标量
matrix_b = matrix_a * 2
print(matrix_b, "\n", "shape=", matrix_b.shape)


[[ 2  4  6]
 [ 8 10 12]] 
 shape= (2, 3)


In [19]:
# 矩阵+标量
matrix_c = matrix_a + 2
print(matrix_c, "\n", "shape=", matrix_c.shape)


[[3 4 5]
 [6 7 8]] 
 shape= (2, 3)


In [20]:
# 矩阵 + 矩阵

matrix_a = np.array([[1, 2, 3], [4, 5, 6]])  # 2行3列
matrix_b = np.array([[-1, -2, -3], [-4, -5, -6]])  # 2行3列

matrix_a + matrix_b


array([[0, 0, 0],
       [0, 0, 0]])

In [21]:
# 矩阵 * 矩阵 (点积) ，对应位置数字相乘，两个矩阵行列数必须相等
matrix_a = np.array([[1, 2, 3], [4, 5, 6]])  # 2行3列
matrix_b = np.array([[-1, -2, -3], [-4, -5, -6]])  # 2行3列
matrix_a * matrix_b  # 和 np.multiply 等价


array([[ -1,  -4,  -9],
       [-16, -25, -36]])

In [22]:
# 矩阵 * 矩阵 (点积) ，对应位置数字相乘，两个矩阵行列数必须相等
matrix_a = np.array([[1, 2, 3], [4, 5, 6]])  # 2行3列
matrix_b = np.array([[-1, -2, -3], [-4, -5, -6]])  # 2行3列
np.multiply(matrix_a, matrix_b)  # * 等价


array([[ -1,  -4,  -9],
       [-16, -25, -36]])

In [25]:
# 矩阵 * 矩阵 (点积) ，对应位置数字相乘，两个矩阵行列数必须相等
matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # 2行3列
matrix_b = np.array([[-1, -2, -3], [-4, -5, -6]])  # 2行3列
matrix_a * matrix_b


ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [27]:
# 矩阵-矩阵乘法(叉乘)

# 如果第一个矩阵列的数量与第二个矩阵行数相匹配，才能将矩阵相乘
# 结果将是一个矩阵，它具有与第一个矩阵相同的行数和与第二个矩阵相同的列数

matrix_a = np.array([[1, 2, 3], [4, 5, 6]])  # 2行3列
matrix_b = np.array([[1, 2, 3, 4], [2, 1, 2, 0], [3, 4, 1, 2]])  # 3行4列

np.matmul(matrix_a, matrix_b)  # 结果是2行4列


array([[14, 16, 10, 10],
       [32, 37, 28, 28]])

In [28]:
# 矩阵-矩阵乘法(叉乘)

# 如果第一个矩阵列的数量与第二个矩阵行数相匹配，才能将矩阵相乘
# 结果将是一个矩阵，它具有与第一个矩阵相同的行数和与第二个矩阵相同的列数

matrix_a = np.array([[1, 2, 3], [4, 5, 6]])  # 2行3列
matrix_b = np.array([[1, 2, 3, 4], [3, 4, 1, 2]])  # 2行4列

np.matmul(matrix_a, matrix_b)  # 报错


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [29]:
# 矩阵向量乘法

# 将矩阵与矢量相乘可以被认为是将矩阵的每一行与矢量的列相乘，矩阵的列数必须等于向量的行
# 输出将是一个具有与矩阵相同行数的向量

matrix_a = np.array([[1, 2, 3], [4, 5, 6]])  # 2行3列
matrix_b = np.array([[1], [2], [3]])  # 3行1列

np.matmul(matrix_a, matrix_b)  # 结果是2行1列


array([[14],
       [32]])

In [30]:
matrix_a = np.array([[1, 2, 3]])  # 1行3列
matrix_b = np.array([[2], [4], [-1]])  # 3行1列

np.matmul(matrix_a, matrix_b)  # 结果是1行1列


array([[7]])

In [31]:
matrix_a = np.array([[1, 2, 3], [4, 5, 6]])  # 2行3列
print(matrix_a, "shape=", matrix_a.shape, "\n", matrix_a.T, "Tshape=", matrix_a.T.shape)


[[1 2 3]
 [4 5 6]] shape= (2, 3) 
 [[1 4]
 [2 5]
 [3 6]] Tshape= (3, 2)


In [33]:
# 行列转置

vector_row = np.array([[1, 2, 3]])

print(
    vector_row,
    "shape=",
    vector_row.shape,
    "\n",
    vector_row.T,
    "Tshape=",
    vector_row.T.shape,
)


[[1 2 3]] shape= (1, 3) 
 [[1]
 [2]
 [3]] Tshape= (3, 1)


In [34]:
# reshape

vector_row = np.array([[1, 2, 3]])
vector_column = vector_row.reshape(3, 1)


print(
    vector_row,
    "shape=",
    vector_row.shape,
    "\n",
    vector_column,
    "reshape=",
    vector_column.shape,
)


[[1 2 3]] shape= (1, 3) 
 [[1]
 [2]
 [3]] reshape= (3, 1)
