In [7]:
import tensorflow as tf

print("TensorFlow版本是：", tf.__version__)

TensorFlow版本是： 2.5.0


In [8]:
node1 = tf.constant([[3.0, 1.5], [2.5, 6.0]], tf.float32)
node2 = tf.constant([[4.0, 1.0], [5.0, 2.5]], tf.float32)
node3 = tf.add(node1, node2)

node3

# 输出的是一个张量Tensor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[7. , 2.5],
       [7.5, 8.5]], dtype=float32)>

In [9]:
print(node3.numpy())

[[7.  2.5]
 [7.5 8.5]]


In [11]:
print(node3.shape)
print(node3.dtype)

(2, 2)
<dtype: 'float32'>


In [13]:
scalar = tf.constant(100)
vector = tf.constant([1, 2, 3, 4, 5])
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
cube_matrix = tf.constant([[[1], [2], [3]], [[4], [5], [6]], [[7], [8], [9]]])

print(scalar.shape)
print(vector.shape)
print(matrix.shape)
print(cube_matrix.get_shape())

()
(5,)
(2, 3)
(3, 3, 1)


In [15]:
print(cube_matrix.numpy()[1, 2, 0])

6


In [16]:
a = tf.constant([1, 2])
b = tf.constant([2.0, 3.0])

ret = tf.add(a, b)

InvalidArgumentError: cannot compute Add as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:Add]

In [20]:
a = tf.constant([1, 2])
b = tf.constant([2.0, 3.0])

a = tf.cast(a, tf.float32)

ret = tf.add(a, b)
# ret.numpy()
print(ret.numpy())

[3. 5.]


In [21]:
a = tf.constant([1, 2])
a

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [22]:
b = tf.constant([1, 2], tf.float32)
b

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [23]:
c = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
c

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [24]:
v1 = tf.Variable([1, 2])
v2 = tf.Variable([3, 4], tf.float32)
v1, v2
# 变量在创建时必须确定初始值，可以像定义常量一样

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 4])>)

In [25]:
c = tf.constant(1)
v = tf.Variable(c)
c, v

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>)

In [26]:
v = tf.Variable(5)
v.assign(v + 1)
v

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=6>

In [28]:
v1 = tf.Variable(5)
v2 = tf.Variable(5)
v1.assign_add(1)
v2.assign_sub(1)
v1, v2

(<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=6>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=4>)

In [29]:
a = tf.constant([1, 2])
a

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

# 在TensorFlow 2.0中实现TensorFlow 1.x的静态图执行模式

In [31]:
import tensorflow.compat.v1 as tf

tf.disable_eager_execution()

In [32]:
node1 = tf.constant(3.0, tf.float32, name="node1")
node2 = tf.constant(4.0, tf.float32, name="node2")
node3 = tf.add(node1, node2)

print(node3)
# 由于是图执行模式，这时仅仅是建立了计算图，但它并没有执行

Tensor("Add:0", shape=(), dtype=float32)


In [33]:
sess = tf.Session()

print("运行sess.run(node1)的结果：", sess.run(node1))
print("运行sess.run(node2)的结果：", sess.run(node2))
print("运行sess.run(node3)的结果：", sess.run(node3))

sess.close()

运行sess.run(node1)的结果： 3.0
运行sess.run(node2)的结果： 4.0
运行sess.run(node3)的结果： 7.0


In [34]:
tens1 = tf.constant([1, 2, 3])
sess = tf.Session()

print(sess.run(tens1))

sess.close()

[1 2 3]


In [35]:
tens1 = tf.constant([1, 2, 3])
sess = tf.Session()
try:
    print(sess.run(tens1))
except:
    print("Exception!")
finally:
    sess.close()

[1 2 3]


In [36]:
tens1 = tf.constant([1, 2, 3])
with tf.Session() as sess:
    print(sess.run(tens1))

[1 2 3]


In [37]:
tens1 = tf.constant([1, 2, 3])
sess = tf.Session()
with sess.as_default():
    print(tens1.eval())

[1 2 3]


In [38]:
tens1 = tf.constant([1, 2, 3])
sess = tf.Session()
print(sess.run(tens1))
print(tens1.eval(session=sess))

[1 2 3]
[1 2 3]


In [39]:
tens1 = tf.constant([1, 2, 3])

sess = tf.InteractiveSession()
print(tens1.eval())

[1 2 3]


In [47]:
import tensorflow.compat.v1 as tf

tf.disable_eager_execution()

hello = tf.constant("Hello, World!")

sess = tf.Session()
print(sess.run(hello))

b'Hello, World!'


In [48]:
node1 = tf.constant(3.0, tf.float32, name="node1")
node2 = tf.constant(4.0, tf.float32, name="node2")
node3 = tf.add(node1, node2)

print(node3)

Tensor("Add_1:0", shape=(), dtype=float32)


In [49]:
sess = tf.Session()

print("运行sess.run(node1)的结果：", sess.run(node1))

运行sess.run(node1)的结果： 3.0


In [50]:
print("运行sess.run(node3)的结果：", sess.run(node3))

sess.close()

运行sess.run(node3)的结果： 7.0


In [2]:
import tensorflow as tf

matrix = tf.constant([[[1, 2], [2, 3]], [[4, 5], [5, 6]]])

print(matrix.shape)

(2, 2, 2)


In [8]:
import tensorflow.compat.v1 as tf

tf.disable_eager_execution()

tf.reset_default_graph()

a = tf.Variable(1, name="a")

b = tf.add(a, 1, name="b")

c = tf.multiply(b, 4, name="c")

d = tf.subtract(c, b, name="d")

logdir = "log"

writer = tf.summary.FileWriter(logdir, tf.get_default_graph())
writer.close()


In [2]:
import tensorflow.compat.v1 as tf

tf.disable_eager_execution()

tf.reset_default_graph()

logdir = "E:/Documents/Codebase/tensorflow/log"

input1 = tf.constant([1.0, 2.0, 3.0], name="input1")
input2 = tf.Variable(tf.random_uniform([3]), name="input2")
output = tf.add_n([input1, input2], name="add")

writer = tf.summary.FileWriter(logdir, tf.get_default_graph())
writer.close()
